meta_product_name: "Song Saviour"
meta_title: "Music lives here"
meta_description: "Music artists buy and sell song rights. Let those songs live even when you can't perform them. Get great songs when you need to fill out your set fast"
meta_image: "cover.png" # should exist in `app/assets/images/`   really???? will Heroku allow this I don't think so 
twitter_account: "@product_twitter_account"   # required for Twitter Cards